name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9" ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wemake-python-styleguide mypy flake8-html

    - name: Static type checking
      if: always()
      run: mypy ./etl

    - name: Finds style issues
      if: always()
      run: flake8 ./etl

    - name: HTML report
      if: always()
      run: |
          flake8 ./etl --per-file-ignores="__init__.py:F401" --format=html --htmldir=lint-report

    - name: Update HTML report
      if: always()
      run: |
          git config --global user.name 'AXlIS'
          git config --global user.email 'axis@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git fetch
          git checkout $GITHUB_HEAD_REF
          git add .
          git commit -m "Update HTML report"
          git push

    - name: Send message to telegram
      if: always()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}

          Repository: ${{ github.repository }}

          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

          Python ${{ matrix.python-version }} version CI status: ${{ job.status }}
